networks:
  app_network:
    driver: bridge

volumes:
  postgres_db_data:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api_container
    build:
      context: .
      dockerfile: API/Dockerfile
    networks:
        - app_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: fleshka5418
      POSTGRES_DB: Project
      POSTGRES_USER: roman
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - app_network
